<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/xhtml; charset=utf-8"/>
    <link href="/build/standalone/lib/mocha/mocha.css" type="text/css" media="screen" rel="stylesheet" />
    <script type="text/javascript" src="/build/standalone/lib/requirejs/require.js"></script>
    <script type="text/javascript">var wed_testing_env=true;</script>
    <script type="text/javascript" src="/config/requirejs-config-dev.js"></script>
  </head>
  <body>
    <div id="mocha"></div>
    <div id="mocha-fixture">
      <div style="display:none">
        <div id="data"></div>
        <div id="domroot"></div>
        <!-- Contain the editor it its own frame so that the styles do
             not mess with those of mocha. -->
      </div>
      <iframe id="wedframe-invisible" width="100%" src="wed_test.html"></iframe>
    </div>
    <script>
      require(["mocha/mocha", "chai", "test/global", "wed/onerror",
               "test/validator_test",
               "test/jquery.findandself_test", "test/refman_test",
               "test/domlistener_test", "test/domutil_test",
               "test/wed_test", "test/input_trigger_test",
               "test/input_trigger_factory_test", "test/tree_updater_test",
               "test/modal_test", "test/jqutil_test"],
              function (mocha, chai, global, onerror) {
          var assert = chai.assert;

          // Reset the server before doing anything.
          before(function (done) {
              global.reset(done);
              onerror.register(window);
          });

          afterEach(function () {
              assert.isFalse(onerror.__test.is_terminating(),
                            "test generated an uncaught exception");
          });
          describe("test-suite", function () {
              // What we are doing here is testing that we are indeed able
              // to detect that an uncaught exception happened while running
              // the test suite because onerror overrides mocha's usual
              // unhandled exception handling.

              // after() might seem more appropriate but to ensure
              // that the order in which this code is run relative to
              // the global afterEach above, we made it an afterEach.
              afterEach(function (done) {
                  assert.isTrue(onerror.__test.is_terminating());
                  onerror.__test.reset();
                  global.reset(done);
              });
              it("failing", function (done) {
                  window.setTimeout(function () {
                      throw new Error("failing on purpose");
                  }, 0);
                  // Make sure we execute **after** the failure.
                  window.setTimeout(function () {
                      done();
                  }, 1);
              });
          });
          mocha.run();
      });
    </script>
  </body>
</html>
